# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_setting.html
#
# Specifies the JVM arguments used for the Gradle daemon.
# One setting to focus on is the max heap size as a project's size grows.
# For a faster build, the daemon is enabled by default.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, see
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#
# AndroidX package structure to make it clearer which packages are part of the Android SDK,
# and which are part of Android's open source libraries (AndroidX).
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
# Kotlin code style for the project: "official" or "obsolete":
kotlin.code.style=official
android.disallowKotlinSourceSets=false
